# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev101+gbf5123f.d20221225'
__version_tuple__ = version_tuple = (0, 1, 'dev101', 'gbf5123f.d20221225')
