# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev105+gc41fe3b.d20230104'
__version_tuple__ = version_tuple = (0, 1, 'dev105', 'gc41fe3b.d20230104')
