# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
<<<<<<< HEAD
version = '0.1.dev57+g27bd363.d20220123'
version_tuple = (0, 1, 'dev57', 'g27bd363.d20220123')
=======
version = '0.1.dev57+g27bd363.d20220119'
version_tuple = (0, 1, 'dev57', 'g27bd363.d20220119')
>>>>>>> 983a25270e5cfb4fafdbcb412b78bf5ffe47729e
