name: basic tests
run-name: ${{ github.actor }} is running basic tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: request python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: unit tests
        run: |
          python -m pip install --upgrade pip
          pip install '.[all]'
          python -m unittest